# Generated by Django 2.2.6 on 2019-10-18 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='image', upload_to='media/'),
            preserve_default=False,
        ),
    ]
