# Generated by Django 2.2.6 on 2019-11-27 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_courseitem_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chapter',
            old_name='category',
            new_name='category_i',
        ),
    ]
