# Generated by Django 2.2.6 on 2019-11-27 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20191127_0709'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseitem',
            old_name='category',
            new_name='category_s',
        ),
    ]
