# Generated by Django 2.2.6 on 2019-11-27 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_courseitem_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseitem',
            name='notes',
            field=models.URLField(blank=True, max_length=100),
        ),
    ]
