# Generated by Django 2.2.6 on 2019-10-21 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20191021_0501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='parent_category',
        ),
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course', to='core.Subcategory'),
        ),
        migrations.AlterIndexTogether(
            name='course',
            index_together={('id', 'slug')},
        ),
        migrations.CreateModel(
            name='CourseItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('lec_name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('video', models.FileField(blank=True, upload_to='media/')),
                ('notes', models.FileField(blank=True, upload_to='media/')),
                ('image', models.ImageField(upload_to='media/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CourseItem', to='core.Course')),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='description',
        ),
        migrations.RemoveField(
            model_name='course',
            name='image',
        ),
        migrations.RemoveField(
            model_name='course',
            name='lec_name',
        ),
        migrations.RemoveField(
            model_name='course',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='course',
            name='video',
        ),
    ]
