# Generated by Django 2.2.6 on 2019-10-21 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20191021_0541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseitem',
            name='image',
        ),
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(default='image', upload_to='media/'),
            preserve_default=False,
        ),
    ]
