# Generated by Django 2.2.6 on 2019-11-29 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20191127_2023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseitem',
            name='notes',
        ),
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(default='', upload_to='')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('file_fk', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.CourseItem')),
            ],
        ),
    ]
