# Generated by Django 2.2.6 on 2019-10-21 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20191021_0545'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseitem',
            name='slug',
            field=models.SlugField(default='slug'),
            preserve_default=False,
        ),
    ]
