# Generated by Django 2.2.6 on 2019-11-30 17:41

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20191129_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseitem',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True),
        ),
    ]
