# Generated by Django 2.2.6 on 2019-12-01 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20191130_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseitem',
            name='github',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='courseitem',
            name='pdf',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.DeleteModel(
            name='FileUpload',
        ),
    ]
