# Generated by Django 2.2.6 on 2019-10-25 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20191025_0725'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='image',
            field=models.ImageField(default='image', upload_to=''),
            preserve_default=False,
        ),
    ]
