# Generated by Django 2.2.6 on 2019-12-01 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20191201_0655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseitem',
            name='pdf',
            field=models.FileField(blank=True, null='True', upload_to=''),
        ),
    ]
