# Generated by Django 2.2.6 on 2019-12-01 08:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20191201_0827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseitem',
            name='github',
            field=models.TextField(blank='True', validators=[django.core.validators.URLValidator()]),
        ),
    ]
