# Generated by Django 2.2.6 on 2019-10-25 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseitem',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CourseItem', to='core.Subcategory'),
        ),
        migrations.AlterField(
            model_name='courseitem',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
