# Generated by Django 2.2.6 on 2019-12-01 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20191201_0830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseitem',
            name='pdf',
            field=models.FileField(null='False', upload_to='media'),
        ),
    ]
