# Generated by Django 2.2.6 on 2019-10-31 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20191028_0956'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ZuserProfile',
        ),
    ]
