# Generated by Django 2.2.6 on 2019-10-31 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_delete_zuserprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseitem',
            old_name='category',
            new_name='categoryi',
        ),
        migrations.RenameField(
            model_name='subcategory',
            old_name='category',
            new_name='categorys',
        ),
    ]
