# Generated by Django 2.2.6 on 2019-11-04 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20191031_1615'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategory',
            old_name='title',
            new_name='name',
        ),
    ]
