# Generated by Django 2.2.6 on 2019-11-04 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20191104_1005'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseitem',
            old_name='title',
            new_name='titalia',
        ),
    ]
