# Generated by Django 2.2.6 on 2019-11-04 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20191104_1006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseitem',
            old_name='titalia',
            new_name='title',
        ),
    ]
