# Generated by Django 2.2.6 on 2019-11-16 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20191104_1008'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subcategory',
            new_name='Units',
        ),
    ]
