# Generated by Django 2.2.6 on 2019-11-16 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20191116_0410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='categorys',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Unit', to='core.Category'),
        ),
    ]
