# Generated by Django 2.2.6 on 2019-11-16 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20191116_0419'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('image', models.ImageField(upload_to='')),
                ('categorys', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Chapter', to='core.Category')),
            ],
            options={
                'verbose_name': 'Chapter',
                'verbose_name_plural': 'Chapters',
            },
        ),
        migrations.AlterField(
            model_name='courseitem',
            name='categoryi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CourseItem', to='core.Chapter'),
        ),
        migrations.DeleteModel(
            name='Unit',
        ),
    ]
