# Generated by Django 2.2.6 on 2019-11-16 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20191116_0444'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chapter',
            old_name='categorys',
            new_name='category_s',
        ),
        migrations.RenameField(
            model_name='courseitem',
            old_name='categoryi',
            new_name='category_i',
        ),
    ]
