# Generated by Django 2.2.6 on 2019-11-26 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20191116_0447'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chapter',
            old_name='category_s',
            new_name='category',
        ),
    ]
