# Generated by Django 2.2.6 on 2019-11-26 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20191126_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapter', to='core.Category'),
        ),
    ]
