# Generated by Django 2.2.6 on 2019-11-26 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20191126_2044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseitem',
            name='category_i',
        ),
        migrations.AddField(
            model_name='courseitem',
            name='category',
            field=models.ForeignKey(default='this is a category', on_delete=django.db.models.deletion.CASCADE, related_name='courseItem', to='core.Chapter'),
            preserve_default=False,
        ),
    ]
