# Generated by Django 2.2.6 on 2019-11-26 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auto_20191126_2047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseitem',
            name='category',
        ),
    ]
