# Generated by Django 2.2.6 on 2019-11-26 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_courseitem_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseitem',
            name='category',
        ),
    ]
