# Generated by Django 2.2.6 on 2019-11-26 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_remove_courseitem_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseitem',
            name='category',
            field=models.ForeignKey(default='hey', on_delete=django.db.models.deletion.CASCADE, related_name='courseitem', to='core.Chapter'),
            preserve_default=False,
        ),
    ]
