# Generated by Django 2.2.6 on 2019-11-26 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_courseitem_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseitem',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
