# Generated by Django 2.2.6 on 2019-11-26 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_auto_20191126_2111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseitem',
            name='category',
        ),
    ]
