# Generated by Django 2.2.6 on 2019-11-26 21:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_remove_courseitem_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseitem',
            name='category',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, related_name='courseitem', to='core.Chapter'),
            preserve_default=False,
        ),
    ]
